In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [6]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [11]:
A = np.random.randn(10)

In [12]:
A

array([ 0.12098545,  0.76725136, -0.94133017,  0.76125356,  0.909906  ,
        0.66503844,  0.23217421,  1.28183994,  0.65180181,  1.49707903])

In [14]:
B = np.random.randn(10)

In [15]:
np.add(A, B)

array([ -4.87815969e-02,   3.09056032e-02,  -8.39208084e-01,
         2.45930141e-01,  -9.90283428e-03,  -3.61564731e-01,
         1.19034902e-03,  -1.35420991e-01,  -3.36255352e-01,
         1.31605987e+00])

In [17]:
np.maximum(A, B)

array([ 0.12098545,  0.76725136,  0.10212209,  0.76125356,  0.909906  ,
        0.66503844,  0.23217421,  1.28183994,  0.65180181,  1.49707903])

In [18]:
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)

True

In [ ]:
import webbrowser
webbrowser.op