In [1]:
import numpy as np

In [2]:
arr = np.arange(5)

In [3]:
arr

array([0, 1, 2, 3, 4])

In [4]:
np.save('myarray', arr)

In [5]:
arr = np.arange(10)

In [6]:
myarray

NameError: name 'myarray' is not defined

In [7]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr1 = np.load('myarray.npy')

In [10]:
arr1

array([0, 1, 2, 3, 4])

In [11]:
arr2 = arr

In [14]:
np.savez('ziparray', x=arr1, y=arr2)

In [15]:
archive_array = np.load('ziparray.npz')

In [16]:
archive_array['x']

array([0, 1, 2, 3, 4])

In [17]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
rm ziparay.npz

SyntaxError: invalid syntax (<ipython-input-18-f71ef4111179>, line 1)

In [19]:
np.savetxt('mytextarray.txt', arr, delimiter=',')

In [20]:
arrx = np.loadtxt('mytextarray.txt', delimiter=',')

In [21]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arrx

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [26]:
import os

In [27]:
os.remove("ziparay.npz")